### ISSUE TITLE
separate treatment for [Adj * float -> Adj] operations

### ISSUE THREAD

**Issue by ghennequin** [gbaydin/DiffSharp#2]
Hi, just a quick remark: it seems that (in some applications) you could save quite a bit by having separate AddFloat / SubFloat / MulFloat / DivFloat variants in Reverse.fs, to treat all four [Adj * float -> Adj] operations. Indeed the adjoint for those float constants is never going to be used; I understand those floats are currently being first converted into Adj and then passed in the Add/Sub/Mul/Div constructs, so their adjoints will actually get computed in the reverse sweep. [I haven't thoroughly read your code so I could well be missing something...]

**Comment by gbaydin** [comment]
Hi, I will look into that. Thank you very much.

**Comment by gbaydin** [comment]
Hi again, I have now fixed this and the unneeded adjoints for constants are not computed anymore. There is a new release (0.5.7) with the fixed reverse code.
