### ISSUE TITLE
potential overwriting of [xa]

### ISSUE THREAD

**Issue by ghennequin** [gbaydin/DiffSharp#3]
In Reverse.ReverseOps.grad', is there anything that prevents the user from modifying some elements of [xa] within the call to [f xa]? (I come from OCaml, and I would guess that with the current formulation, elements of [xa] could be modified, which would then lead to [Array.map adjoint xa] reading the wrong adjoint values; but perhaps there's something specific to F# I'm missing here)

**Comment by gbaydin** [comment]
Thank you for pointing this out. I think you are right, as I made the choice of using arrays in the API, there seems to be no way of preventing the user from overwriting the elements of the input array in the function. We just assume that the user's function will be "well-behaved" and will carry the computation forward from the inputs to the output. Using lists, instead of arrays, could be a way of solving this with immutability. But my understanding is that they have poor performance in this task.

**Comment by ghennequin** [comment]
In Ocaml, I would merely copy the array `xa` before passing it to `f`, and then read the adjoints in the copy after the reverse sweep. This would prevent one source of errors, in which the user uses the memory space in `x` to put results of otherwise well-behaved operations. It wouldn't prevent the user from modifying `xa` before operating on it, but that's more the user's responsibility indeed.

**Comment by gbaydin** [comment]
I see. But, I think the array `xa` is already just an internal a copy of the user's array `x`, through `let xa = Array.map adj x`.

**Comment by ghennequin** [comment]
yes, but you don't want a copy of `x`, but really a copy of the adjoint part; so I guess you ought to send a copy of `xa` to f.

**Comment by gbaydin** [comment]
I made some experiments with
```
let inline grad' f x =
    Trace.Clear()
    let xa = Array.map adj x
    let xaa = Array.copy xa
    let z:Adj = f xa
    z.A <- 1.
    Trace.ReverseSweep()
    (primal z, Array.map adjoint xaa)

let inline f (x:_[]) =
    let a = x.[1]
    x.[1] <- x.[2]
    x.[2] <- a
    sin (x.[0] + x.[1]) * x.[2]

let g = grad' f [|1.; 2.; 3.|]
```

I think now I understand what you mean. I don't want to complicate the code at this stage for covering for this possibility, but I will keep this in mind. Thank you. :)

**Comment by barak** [comment]
This seems to me like an intrinsic problem with trying to do reverse-mode AD in a language with mutation. You can either (a) live with the possibility of the sands shifting beneath you halfway through the computation, or (b) copy the state, just in case, and suffer with that overhead.
